version: "3.7"

services:
  frontend:
    build: streamlit_frontend
    ports:
      - 8501:8501
    networks: 
      AIservice: 
        aliases: 
          - frontend.docker
    depends_on:
      - backend
    volumes:
        - ./streamlit_frontend:/app
        - ./storage:/storage

  backend:
    build: fastAPI_backend
    ports:
      - 8000:8000
    networks: 
      AIservice: 
        aliases: 
          - backend.docker
    volumes:
      - ./fastAPI_backend:/app
      - ./storage:/storage

  orion-ld:
    image: fiware/orion-ld
    hostname: orion-ld
    container_name: fiware-orion-ld

    networks: 
      AIservice: 
        aliases: 
          - orion.docker
    expose:
      - "1027"
    ports:
      - "1027:1027"
    depends_on:
      - mongo-database
    command: -dbhost mongo.docker -logLevel DEBUG -port 1027

  mongo-database:
    image: mongo:3.6
    hostname: mongo-database
    container_name: database-mongo
    ports:
      - "27018:27018" 
    networks: 
      AIservice: 
        aliases: 
          - mongo.docker
    command: --nojournal
    volumes:
      - mongo-database:/database#

    # @context file is served from here
  ngsi-ld-context:
    image: httpd:alpine
    container_name: ld-context
    networks: 
      AIservice: 
        aliases: 
          - context
    ports:
        - "3004:80"
    volumes:
        - ./data-models:/usr/local/apache2/htdocs/

networks:
  AIservice:
    external: true
volumes:
  mongo-database: ~